path_JPEGImages=r'/Volumes/One Touch/Images_gdrive/Drone_Images/Training/JPEGImages' #default JPEGImages directory
path_Annotations=r'/Volumes/One Touch/Images_gdrive/Drone_Images/Training/Annotations' #default Annotations directory
path_labelImg=r'/Volumes/One Touch/labelImg/labelImg.py' #path to labelImg.py
root_background_img=r'misc/gradient_green.jpg' #path to background image for app
predefined_classes='predefined_classes.txt' #created when using labelImg.py
DEFAULT_ENCODING = 'utf-8'
XML_EXT = '.xml'
JPG_EXT = '.jpg'
PYTHON_PATH = 'python3'
W=100
H=100
MOSAIC_NUM=200
FIGSIZE_W=50
FIGSIZE_H=50
FIGSIZE_INCH_W=8
FIGSIZE_INCH_H=8
COLOR='red'
root_bg='#000000'#'black'
root_fg='#b7f731'#'lime'
canvas_columnspan=50
canvas_rowspan=50
