path_JPEGImages=r'/Volumes/One Touch/CustomDroneVideo_mp4/IMG_4305_frames/MODEL_efficientdet1_VisDrone_efficientdet1_100epochs-1tpus-VisDrone_edgetpu/JPEGImages'
path_Annotations=r'/Volumes/One Touch/CustomDroneVideo_mp4/IMG_4305_frames/MODEL_efficientdet1_VisDrone_efficientdet1_100epochs-1tpus-VisDrone_edgetpu/Annotations'
path_labelImg=r'/Volumes/One Touch/labelImg-Custom/labelImg.py'
root_background_img=r'misc/gradient_green.jpg'
predefined_classes='predefined_classes.txt'
DEFAULT_ENCODING ='utf-8'
XML_EXT ='.xml'
JPG_EXT ='.jpg'
PYTHON_PATH ='python3'
W=100
H=100
MOSAIC_NUM=50
FIGSIZE_W=50
FIGSIZE_H=50
FIGSIZE_INCH_W=8
FIGSIZE_INCH_H=8
COLOR='red'
root_bg='#000000'
root_fg='#b7f731'
canvas_columnspan=50
canvas_rowspan=50
